"""Abstract database interface used by the repository layer.

The repositories below only know about this protocol, which means they can be
unit-tested with the in-memory :class:`app.repositories.fake.FakeFirestore`
while running against the real Firestore client in production.
"""
from __future__ import annotations

from contextlib import contextmanager
from typing import Any, Callable, Iterable, Iterator, Optional, Protocol


class Database(Protocol):
    """Subset of Firestore operations the application needs."""

    @property
    def supports_transactions(self) -> bool: ...

    def collection(self, name: str) -> "Collection": ...

    def transaction(self) -> "Transaction": ...


class Collection(Protocol):
    def document(self, doc_id: Optional[str] = None) -> "Document": ...
    def add(self, data: dict) -> tuple["Document", str]: ...
    def where(self, field: str, op: str, value: Any) -> "Query": ...
    def order_by(self, field: str, direction: Optional[str] = None) -> "Query": ...
    def limit(self, count: int) -> "Query": ...
    def stream(self) -> Iterable["Document"]: ...
    def get(self) -> list["Document"]: ...


class Document(Protocol):
    id: str
    parent: Collection

    def get(self) -> "Document": ...
    def set(self, data: dict, merge: bool = False) -> None: ...
    def update(self, data: dict) -> None: ...
    def delete(self) -> None: ...
    @property
    def exists(self) -> bool: ...
    def to_dict(self) -> dict: ...


class Query(Protocol):
    def where(self, field: str, op: str, value: Any) -> "Query": ...
    def order_by(self, field: str, direction: Optional[str] = None) -> "Query": ...
    def limit(self, count: int) -> "Query": ...
    def stream(self) -> Iterable[Document]: ...
    def get(self) -> list[Document]: ...


class Transaction(Protocol):
    def get(self, ref: Document) -> Document: ...
    def set(self, ref: Document, data: dict, merge: bool = False) -> None: ...
    def update(self, ref: Document, data: dict) -> None: ...
    def delete(self, ref: Document) -> None: ...